### ISSUE TITLE
error

### ISSUE THREAD

**Issue by liamxg** [niemasd/tools#1]
base) simon@192 Figure1 % python fasta_subsample.py -h   
Traceback (most recent call last):
  File "/Volumes/ZJJ/0_GISAID/20231216/Figure1/fasta_subsample.py", line 10, in <module>
    from common import readFASTA
ImportError: cannot import name 'readFASTA' from 'common' (/Users/simon/opt/miniconda3/lib/python3.9/site-packages/common/__init__.py)

**Comment by niemasd** [comment]
Did you clone the complete repository? The `fasta_subsample.py` script relies on functions in the `common.py` script in this same repo

**Comment by liamxg** [comment]
Dear @niemasd, 
thanks. 

zsh: killed     python fasta_subsample.py -i hiv.fa -o 1.fas -p 0.001

**Comment by liamxg** [comment]
automate killed.

**Comment by liamxg** [comment]
before you told me, I install the common using `pip install common`.

**Comment by liamxg** [comment]
Any script for extract fasta sequences from a MAS fasta file base on sequence name, thanks.

**Comment by niemasd** [comment]
In Unix shells, `Killed` usually means the program used more memory than your environment has available. My `subsample_fasta.py` script loads all of the sequences in memory all at once, and then it randomly subsamples it in memory. If it's getting killed on your dataset, your dataset is too large to fit in memory, and you'll need to use some other tool that doesn't load everything in memory (or you'll need to write your own). I don't have any specific tools already written that do what you're asking; sorry!

**Comment by liamxg** [comment]
Dear @niemasd,

Thanks, really cool tools.
